Parse cmd line args
kszytko/testing pull request #12
Opened 2020-08-21 08:36 UTC by niemarcin

Close #5 ; Close #6

2020-08-21 22:08 UTC, kszytko requested changes
Some small changes to make

2020-08-21 22:08 UTC, kszytko commented on bowling/src/ArgumentParser.cpp
> +    return argv_[1];
```suggestion
    if (argc_ == 1) 
        return "";
    return argv_[1]; 
```

2020-08-21 22:08 UTC, kszytko commented on bowling/src/ArgumentParser.cpp
> +    return argv_[2];
```suggestion
    if (argc_ <= 2) 
        return "";
    return argv_[2]; 
```
Duplicate code in `getInputDirectory`. You can extract method.

2020-08-21 22:08 UTC, kszytko commented on bowling/src/ArgumentParser.cpp
> +bool ArgumentParser::cmdOptionExists(const std::string& option) const {
Better name `argumentExists`

2020-08-21 22:08 UTC, kszytko commented on bowling/inc/ArgumentParser.hpp
> +private:
private variables should be on the bottom of the class, based on C++ code style

2020-08-23 14:31 UTC, niemarcin commented on bowling/src/ArgumentParser.cpp
> +    return argv_[2];
I don't know if it's worth to extract a method here. Especially with your proposed changes and different comparison operators: `==` in `getInputDirectory()` and `<=` in `getOutputFileName()`. I'd rather stick with simple `if - return`  statement as it is.

2020-08-25 15:09 UTC, kszytko requested changes
Some small changes i think to make,  consider updates in tests but not so important.

2020-08-25 15:09 UTC, kszytko commented on bowling/inc/ArgumentParser.hpp
> +    int argc_;
If you want to parse argc into your class, make better name, like size_.

2020-08-25 15:09 UTC, kszytko commented on bowling/inc/ArgumentParser.hpp
> +    std::vector<std::string> argv_{};
same here,  arguments_

2020-08-25 15:09 UTC, kszytko commented on bowling/inc/ArgumentParser.hpp
> +    std::string appName_{};
Do we really need app name?

2020-08-25 15:09 UTC, kszytko commented on bowling/test/ArgumentParser-ut.cpp
> +    ArgumentParser ap{argumentsCounter, argumentsArray};
In all tests you have a lot of duplicated code, so you can consider to use TEST_F with predefined parameters, and some functions like `calculateArgumentsSize`

2020-08-25 15:09 UTC, kszytko commented on bowling/src/ArgumentParser.cpp
> +    return argv_[1];
Practicly you return first argument if exists,  in `getOutputFileName` you are returning secound argument if exists.  
It's good to make it into small function like this:

```cpp
std::string getExistingArgument(size_t number) {
    if (size >= number)
        return arguments_[number - 1];
    return ""; 
}

what do you think?
```

2020-08-25 16:36 UTC, kszytko requested changes
Some more changes to discuss

2020-08-25 16:36 UTC, kszytko commented on bowling/src/ArgumentParser.cpp
> +    }
Move it into private method `void makeVector(array)`, now it is not readable

2020-08-25 16:36 UTC, kszytko commented on bowling/src/ArgumentParser.cpp
> +ArgumentParser::ArgumentParser(int argc, char** argv) {
```suggestion
ArgumentParser::ArgumentParser(int size, char** arguments)  : size_(size){
makeVector(arguments);
```

2020-08-25 16:36 UTC, kszytko commented on bowling/src/ArgumentParser.cpp
> +    appName_ = argv_[0];
If you really want to save name of file,  make private method `readAppName();`

2020-08-26 18:30 UTC, niemarcin commented on bowling/test/ArgumentParser-ut.cpp
> +    ArgumentParser ap{argumentsCounter, argumentsArray};
Yes, I know. 
I'd like to refactor it later, if I had enough time for it. Until then the code is tested with current tests, so I'd like to provide the parser to other members of our group.

But you're absolutely right that TEST_F should happen here. ;)

2020-08-26 19:55 UTC, kszytko approved these changes
Very good code!  Only tests to future update

2020-08-30 13:03 UTC, mariuszlisowski approved these changes

2020-08-30 13:03 UTC, mariuszlisowski commented on bowling/src/ArgumentParser.cpp
> +    for (int i = 0; i < size_; ++i) {
size_t instead of int because 'size' variable is of size_t type

2020-08-30 13:03 UTC, mariuszlisowski commented on bowling/src/ArgumentParser.cpp
> +     return size_ == 1 || size_ > 3 || argumentExists("-h") || argumentExists("--help");
There's no difference if program is executed with -h option or without any arguments so the option -h seems useless (help is displayed anyway). Unless when executing without any arguments it shows only short description of its purpose and offers -h option for more details. If so the 'size_ == 1' condition is  redundant. But it's really nothing and can be left as it is.

2020-08-30 18:31 UTC, merged