Kszytko
kszytko/testing pull request #20
Opened 2020-09-24 20:09 UTC by kszytko

One year after :D

2020-09-27 17:03 UTC, niemarcin requested changes
One of our "actions" is checking code formatting and it didn't pass. Sometimes there are things like `class Name{`, sometimes you have inconsistent order of includes. All in all, would be nice if "lint" action pass. :) 

Where I wrote about passing references instead of copying values, please take a look because maybe even const reference would be possible and better.

2020-09-27 17:03 UTC, niemarcin commented on bowling/inc/printableData.hpp
> +};
In most (or even in all) other places we use convention where variables with underscore at the end are members of the class. Here is the opposite.  I'd rather stick with one convention, even though here we have structs, not classes, but the idea is the same.

2020-09-27 17:03 UTC, niemarcin commented on bowling/inc/printerStream.hpp
> +class PrinterStream{
`{` formatting

2020-09-27 17:03 UTC, niemarcin commented on bowling/inc/printerStream.hpp
> +    virtual void print(std::string stream) = 0;
Can we pass it as string& instead of string copy?  Of course it then should be changed in derived classes.

2020-09-27 17:03 UTC, niemarcin commented on bowling/inc/printerStream.hpp
> +    virtual void print(size_t value) = 0;
Maybe names  "stringToPrint" and "valueToPrint" would be better?  It's strange in derived classes to have for example `std::string stream` and `std::ostringstream stream_` where `stream` is not really a stream.

2020-09-27 17:03 UTC, niemarcin commented on bowling/inc/consoleStream.hpp
> +    std::string str() const ;
`;` formatting

2020-09-27 17:03 UTC, niemarcin commented on bowling/inc/consoleStream.hpp
> +class ConsoleStream : public PrinterStream{
`{` formatting

2020-09-27 17:03 UTC, niemarcin commented on bowling/inc/printerStream.hpp
> +public:
Shouldn't we have virtual destructor in this class?

2020-09-27 17:03 UTC, niemarcin commented on bowling/inc/fileStream.hpp
> +    FileStream(std::string filePath);
Maybe string& instead of string?

2020-09-27 17:03 UTC, niemarcin commented on bowling/inc/fileStream.hpp
> +    std::ofstream * file_;
Why is it stored as a pointer instead of just `std::ofstream file_;` ?

2020-09-27 17:03 UTC, niemarcin commented on bowling/inc/printer.h
> +    void printText(size_t value);
If one method prints text and another prints value then maybe it's better to name them "print" instead of "printText", because it can be also a value, not only a text?

2020-09-27 17:03 UTC, niemarcin commented on bowling/inc/printer.h
> +    void print(std::vector<LaneStruct> lanes);
I would pass lanes as a reference.

2020-09-27 17:03 UTC, niemarcin commented on bowling/inc/printer.h
> +};
It seems that these methods could be marked as const as they don't modify the object itself:

```
public:
    void print(std::vector<LaneStruct>& lanes) const;
private:
    void printHeader(LaneStruct & lane) const ;
    void printText(std::string text) const;
    void printText(size_t value) const;
    std::string parseStatus(const Status status) const;
    void printPlayers(LaneStruct & lane) const;
    void printPlayer(Player & player) const;
```

What's more they can even take const references as parameters, not just references.

2020-09-27 17:03 UTC, niemarcin commented on bowling/test/printer-ut.cpp
> +    ASSERT_EQ(oss->str(), "### :  ###\n");
You could add `output` variable as in other test cases.

2020-09-27 17:03 UTC, niemarcin commented on bowling/test/printer-ut.cpp
> +TEST_F(PrinterTest, givenMultipleLines_ShouldPrintValidHeaders) {
In test name Lines -> Lanes ;)

2020-09-27 17:03 UTC, niemarcin commented on bowling/test/printer-ut.cpp
> +TEST_F(PrinterTest, givenMultipleLinesWithMultiplePlayers_ShouldPrintValidHeaders) {
In test name Lines -> Lanes ;)

2020-09-27 17:03 UTC, niemarcin commented on bowling/inc/printer.h
> +    PrinterStream * stream_;
Should we call "delete" on this pointer in Printer destructor?

2020-09-27 17:03 UTC, niemarcin commented on bowling/test/printer-ut.cpp
> +    printer = new Printer(new FileStream(fileName));
Should we call delete somewhere to avoid memory leaks?

2020-09-27 22:42 UTC, niemarcin commented
@kszytko one more thing:  you have printer.h, not .hpp file - is it done intentionally?

2020-09-28 13:17 UTC, kuchichan requested changes
Good code, minor things to consider.

2020-09-28 13:17 UTC, kuchichan commented on bowling/inc/fileStream.hpp
> +    FileStream(std::string filePath);
+1 (even `const`)

2020-09-28 13:17 UTC, kuchichan commented on bowling/src/printer.cpp
> +    printText("### " + lane.name + ": " + parseStatus(lane.status) + " ###\n");
You can exctract `###` to  constexpr. What is more, if you are concatenate more than 2 strings, use `append()` or string stream :)

2020-10-25 15:52 UTC, merged